config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'landing#main'
  
  get 'plano_de_estudo' => 'landing#painel'
  
  
  
  get 'provas_e_simulados' => 'apostilas#apostilas'
  get '/provas_e_simulados/:apostila/', to: 'apostilas#apostila'
  get '/provas_e_simulados/:apostila/:indice', to: 'apostilas#pagina'
  get '/corrige_cartao/:apostila', to: 'apostilas#corrige_cartao'
  
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'login' => 'landing#login'
  
  get '/topicos/adiciona_apostila/:apostila/:topico', to: 'topicos#adiciona_apostila'
  get '/topicos/remove_apostila/:apostila/:topico', to: 'topicos#remove_apostila'
  get '/material_de_estudo/', to: 'assuntos#assuntos'
  get '/material_de_estudo/:assunto', to: 'assuntos#assunto'
  get '/material_de_estudo/flashcards/:nome_do_deck', to: 'decks#show_por_titulo'
  
  get '/flashcard/img/:id', to: 'flashcards#img'

  
  get 'landing/main'
  
  get '/blog', to: 'blog#inicio'
  get '/marktex_editor/', to: 'blog#marktex_editor'
  

  get 'adiciona_questao/:questao/:apostila', to: 'apostilas#adiciona_questao' #AJAX
  get 'remove_questao/:questao/:apostila', to: 'apostilas#remove_questao' #AJAX

  get 'assuntos/adiciona/:assunto/:questao', to: 'questoes#add_assunto'
  get 'assuntos/remove/:assunto/:questao', to: 'questoes#rem_assunto'
  get 'questao/define_gabarito/:id/:gabarito', to: 'questoes#define_gabarito' #AJAX
  get 'questao/exibir_formulario/:id', to: 'questoes#modal_classificacao' #AJAX
  get '/importar_questoes', to: 'questoes#importar'
  
  get 'sessions/novo-curso/:novo_curso', to: 'sessions#seleciona_curso'
  
  resources :respostas
  resources :questoes
  
  scope '/admin' do
    resources :assuntos
    resources :taticas
    resources :cartoes
    resources :flashcards
    resources :comentarios
    resources :cursos
    resources :topicos
    resources :apostilas
    resources :decks
    resources :concursos
    resources :respostas_fs
    resources :semanas
    resources :estudos
  end

end

app/models/comentario.rb
class Comentario
  include Mongoid::Document
  include Mongoid::Timestamps
  field :texto, type: String
  
  default_scope { order_by(:created_at => 'asc') }
  
  belongs_to :user
  belongs_to :topico
  belongs_to :questao
  
  def dono
    if self.questao != nil
      self.questao
    elsif self.topico != nil
      self.topico
    end
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  def por_questao
    @questao = Questao.find(params[:questao_id])
    @comentario = Comentario.new questao: @questao.id
  end

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.js { render "comentario_salvo" }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.js { render "comentario_atualizado" }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
      format.js { render "comentario_excluido" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:user_id, :texto, :topico_id, :questao_id)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentarios.html.erb
<h5 class="ui top attached block header">Comentários</h5>
<div class="ui bottom attached segment">
  <div class="ui comments" id="comentarios_d_<%=@questao.id%>">
    <%if @questao.comentarios.size > 0%>
      <%@questao.comentarios.each do |c|%>
        <%= render partial: 'comentarios/show_externo', locals: {c: c}%>            
      <%end%>
    <%end%>
    </div>
    <div class="form comentario">
    <%= render partial: 'comentarios/form_externo', locals:{questao: @questao}%>
  </div>
</div>

app/views/comentarios/_form.html.erb
<%= simple_form_for(@comentario) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id%>
    <%= f.input :texto %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comentarios/_form_externo.html.erb
<%= simple_form_for(@comentario, remote: true, :html => {id: "form_#{@comentario.dono.id}"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden, :input_html => { value: current_user.id } %>
    <%if !local_assigns[:topico].nil?%>
      <%= f.input :topico_id, as: :hidden, :input_html => { value: topico.id } %>
    <%end%>
    <%if !local_assigns[:questao].nil?%>
      <%= f.input :questao_id, as: :hidden, :input_html => { value: questao.id } %>
    <%end%>
    <%= f.input :texto, label: 'Deixe o seu comentário a respeito:', as: :text, :input_html => {id: "textbox_#{@comentario.dono.id}"}%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, id: "submit_#{@comentario.dono.id}" %>
  </div>
<% end %>

app/views/comentarios/_show_externo.html.erb
<div class="comment" id="<%=c.id%>">
  <a class="avatar">
    <img src="<%=c.user.image_url%>">
  </a>
  <div class="content">
    <a class="author"><%=c.user.name%></a>
    <div class="metadata">
      <div class="date"><%=c.created_at.strftime('%d/%m/%y')%></div>
    </div>
    <div class="text" id="texto_<%=c.id%>">
      <%=c.texto.markdown_to_html%>
    </div>
    <div class="actions">
      <%if c.user.id = current_user.id%>
        <a id="editar_<%=c.id%>" class="action_editar">Editar</a>
        <%= link_to 'Excluir', c, method: :delete, data: { confirm: 'Você tem certeza que deseja excluir o comentário? Essa ação não poderá ser desfeita.', remote: true } %>
      <%end%>
    </div>
    <div id="form_<%=c.id%>">
    </div>
  </div>
</div>

<script>
  $('#editar_<%=c.id%>').click(function(){
    var texto = $('#texto_<%=c.id%>').text();
    texto = texto.replace(/<[^>]*>\s/g, "");
    texto = texto.trim();
    
    $('#textbox_<%="#{c.dono.id}"%>').focus();
    $('#textbox_<%="#{c.dono.id}"%>').val(texto);
    $('#form_<%="#{c.dono.id}"%>').attr('action', '/comentarios/<%=c.id%>');
    $('#form_<%="#{c.dono.id}"%>').attr('method', 'put');
  });
</script>

app/views/comentarios/comentario_atualizado.js.erb
$('#textbox_<%="#{@comentario.dono.id}"%>').val('');
$('#form_<%="#{@comentario.dono.id}"%>').attr('action', '/comentarios');
$('#form_<%="#{@comentario.dono.id}"%>').attr('method', 'post');
$('#<%=@comentario.id%>').transition('pulse');
$('#texto_<%=@comentario.id%>').html('<%= j @comentario.texto.markdown_to_html%>');

app/views/comentarios/comentario_excluido.js.erb
$('#<%=@comentario.id%>').remove();

app/views/comentarios/comentario_salvo.js.erb
$('#comentarios_d_<%=@comentario.dono.id%>').append('<%= j render partial: 'comentarios/show_externo', locals: {c: @comentario} %>');
$('#<%=@comentario.id%>').transition('pulse');
$('#textbox_<%="#{@comentario.dono.id}"%>').val('');

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.user_id %></td>
        <td><%= comentario.texto %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/por_questao.js.erb
$('#comentarios_<%=@questao.id%>').html('<%= j render "comentarios"%>');
$('#exibe_comm_<%=@questao.id%>').hide();
$('#esconde_comm_<%=@questao.id%>').show();

app/views/comentarios/show.html.erb
<div class="ui main container">
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comentario.user %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @comentario.texto %>
</p>

<p>
  <strong>Topico</strong>
  <%= @comentario.topico %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>
</div>