config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'landing#main'
  
  get 'plano_de_estudo' => 'landing#painel'
  
  
  
  get 'provas_e_simulados' => 'apostilas#apostilas'
  get '/provas_e_simulados/:apostila/', to: 'apostilas#apostila'
  get '/provas_e_simulados/:apostila/:indice', to: 'apostilas#pagina'
  get '/corrige_cartao/:apostila', to: 'apostilas#corrige_cartao'
  
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'login' => 'landing#login'
  
  get '/topicos/adiciona_apostila/:apostila/:topico', to: 'topicos#adiciona_apostila'
  get '/topicos/remove_apostila/:apostila/:topico', to: 'topicos#remove_apostila'
  get '/material_de_estudo/', to: 'assuntos#assuntos'
  get '/material_de_estudo/:assunto', to: 'assuntos#assunto'
  get '/material_de_estudo/flashcards/:nome_do_deck', to: 'decks#show_por_titulo'
  
  get '/flashcard/img/:id', to: 'flashcards#img'

  
  get 'landing/main'
  
  get '/blog', to: 'blog#inicio'
  get '/marktex_editor/', to: 'blog#marktex_editor'
  

  get 'adiciona_questao/:questao/:apostila', to: 'apostilas#adiciona_questao' #AJAX
  get 'remove_questao/:questao/:apostila', to: 'apostilas#remove_questao' #AJAX

  get 'assuntos/adiciona/:assunto/:questao', to: 'questoes#add_assunto'
  get 'assuntos/remove/:assunto/:questao', to: 'questoes#rem_assunto'
  get 'questao/define_gabarito/:id/:gabarito', to: 'questoes#define_gabarito' #AJAX
  get 'questao/exibir_formulario/:id', to: 'questoes#modal_classificacao' #AJAX
  get '/importar_questoes', to: 'questoes#importar'
  
  get 'sessions/novo-curso/:novo_curso', to: 'sessions#seleciona_curso'
  
  resources :respostas
  resources :questoes
  
  scope '/admin' do
    resources :assuntos
    resources :taticas
    resources :cartoes
    resources :flashcards
    resources :comentarios
    resources :cursos
    resources :topicos
    resources :apostilas
    resources :decks
    resources :concursos
    resources :respostas_fs
    resources :semanas
    resources :estudos
  end

end

app/models/deck.rb
class Deck
  include Mongoid::Document
  include Mongoid::Timestamps
  field :titulo, type: String
  field :link, type: String
  field :descricao, type: String
  field :topicos, type: Array, default: []

  belongs_to :user
  has_many :flashcards
  has_many :cartoes
  belongs_to :assunto

  before_save :set_link

  def set_link
    if self.link == nil || self.link == '' then self.link = CGI.escape(self.titulo) end
  end

  def to_item
	  item = {
	    titulo: self.titulo,
	    descricao: self.descricao,
	    link: 'flashcards/'+self.titulo,
      tipo: self.class.to_s,
      icone: 'images outline',
      obj: self,
	    criado_em: self.created_at,
	    atualizado_em: self.updated_at 
	  }
  end

  def topicos_obj
    Topico.where(:id.in => self.topicos)
  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]
  before_action :set_assuntos, only: [:edit, :new]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
    user = current_user
    #Para carregar o desempenho anterior, basta definir o cartão
    @cartao = Cartao.find_or_create_by(user_id: user.id, deck_id: @deck.id)
    #@cartao = Cartao.create! user_id: current_user.id, deck_id: @deck.id
    
    @resposta_por_flashcard = PreparaCartao.resposta_por_flashcard @cartao

    @desempenho = user.desempenho_por_cartao @cartao.id
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
    @flashcard = Flashcard.new
    @flashcard.deck_id = @deck.id
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      if params[:id].present?
        @deck = Deck.find(params[:id])
      elsif params[:nome_do_deck].present?
        @deck = Deck.find_by(titulo: params[:nome_do_deck])
      end
    end

    def set_assuntos
      @assuntos = Assunto.all
      @topicos = Topico.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:titulo, :user_id, :assunto_id, :descricao, topicos: [])
    end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= simple_form_for(@deck) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
    <%= f.input :titulo %>
    <%= f.input :descricao %>
    <%= f.input :assunto_id, collection: @assuntos %>
    <%= f.input :topicos, collection: @topicos, label_method: :to_label, warpper_html: { class: 'input' },
        as: :check_boxes%>
    <%= f.button :submit %>
  </div>
<% end %>

<% if !@deck.new_record? %>
	<div class="ui segment">
		<h3>Flashcards</h3>
		<%=exibe_flashcards @deck.flashcards %>

		<div class="ui divider"></div>
		<%= render "flashcards/form" %>
	</div>
<%end%>

app/views/decks/_show.html.erb
<div class="ui main grid container" >
  <%= exibe_header "Flashcards", "material", [] %>

  <div class="row">
  	<div class="ui segment">
			<h3>Flashcards</h3>
			<%=exibe_flashcards @deck.flashcards %>

			<div class="ui divider"></div>
			<%= render "flashcards/form" %>
		</div>
  </div>
</div>>

app/views/decks/edit.html.erb
<div class="ui main grid container" >
	<%= exibe_header "Editar Deck", "material", [] %>
	<%= render 'form' %>

	<%= link_to 'Show', @deck %> |
	<%= link_to 'Back', decks_path %>
</div>

app/views/decks/index.html.erb
<div class="ui main grid container">
<p id="notice"><%= notice %></p>

<h1>Listing Decks</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>User</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.titulo %></td>
        <td><%= deck.user_id %></td>
        <td><%= deck.descricao %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>
</div>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<div class="ui main grid container" data-controller="slideshow" data-slideshow-index="0">

  <%= exibe_header "Flashcards", "material", [] %>
  <p id="notice"><%= notice %></p>


	<div id="row_deck" class="ui row">
		
		<div class="four wide column">
			<div id="side_segment" class="ui inverted segment">

				<div class="ui dividing inverted header">
					<div class="content">
				    <%=@deck.titulo%>
				    <div class="sub header">Criado por: <strong><%=@deck.user.name%></strong></div>
				  </div>
				</div>

				<div class="ui horizontal small inverted statistics">
				  <div class="statistic">
				    <div id="nao_acertei" class="value">
				      <%=@desempenho[:erros]%>
				    </div>
				    <div class="label">
				      Não Acertei
				    </div>
				  </div>
				  <div class="statistic">
				    <div id="acertei_com_dificuldade" class="value">
				      <%=@desempenho[:quases]%>
				    </div>
				    <div class="label">
				      Acertei com dificuldade
				    </div>
				  </div>
				  <div class="statistic">
				    <div id="acertei" class="value">
				      <%=@desempenho[:acertos]%>
				    </div>
				    <div class="label">
				      Acertei
				    </div>
				  </div>
				</div>

				<div class="ui divider"></div>

				<a class="ui fluid teal button">Finalizar</a>

			</div>

			<%if current_user.admin? %>
				<%= link_to 'Edit', edit_deck_path(@deck) %> | 
				<%= link_to 'Back', decks_path %>
			<%end%>
		</div>
		
		<div class="ten wide column" >
			<%curso = curso_atual.id.to_s%>
			<%user = current_user.id%>
			<%@resposta_por_flashcard.each do |rf|%>
				<%= render partial: "flashcards/show", locals: {flashcard: rf[:flashcard], curso: curso, 
																														resposta: rf[:resposta], user: user,
																														deck: @deck.id, cartao: @cartao.id} %>
			<%end%>
			
		</div>

	</div>

	<div id="row_deck_menu" class="ui row">
		<div class="four wide column"></div>
		<div class="ten wide column">
			<div class="ui secondary five item menu">
			  <a id="botao_anterior" class="item" data-action="slideshow#previous">
			    <i class="chevron left icon"></i>
			  </a>
			  <a class="disabled item" data-target="slideshow.virar">
			    
			  </a>
			  <a class="item" data-target="slideshow.virar" data-action="click->slideshow#flip">
			    <i class="undo icon"></i>
			  </a>			  
			  <a class="disabled item" data-target="slideshow.virar">
			    
			  </a>
			  <a class="active item escondido" data-target="slideshow.respondido" data-desemp="1" data-action="slideshow#desempenho">
					Não Acertei
			  </a>
			  <a class="item escondido" data-target="slideshow.respondido" data-desemp="2" data-action="slideshow#desempenho">
			    Acertei com dificuldade
			  </a>
			  <a class="item escondido" data-target="slideshow.respondido" data-desemp="3" data-action="slideshow#desempenho">
			    Acertei
			  </a>
			  <a id="botao_proximo" class="item" data-action="slideshow#next">
			    <i class="chevron right icon"></i>
			  </a>
			</div>
			<div id="deck_progress" class="ui teal small progress" data-target="slideshow.progress">
			  <div class="bar">
			    <div class="progress"></div>
			  </div>
			</div>
		</div>
	</div>
</div>

<%= content_for :head do %>
	<%= stylesheet_link_tag 'flashcards', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'flashcards', media: 'all', 'data-turbolinks-track' => true %>
<%end%>