config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'landing#main'
  
  get 'plano_de_estudo' => 'landing#painel'
  
  
  
  get 'provas_e_simulados' => 'apostilas#apostilas'
  get '/provas_e_simulados/:apostila/', to: 'apostilas#apostila'
  get '/provas_e_simulados/:apostila/:indice', to: 'apostilas#pagina'
  get '/corrige_cartao/:apostila', to: 'apostilas#corrige_cartao'
  
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'login' => 'landing#login'
  
  get '/topicos/adiciona_apostila/:apostila/:topico', to: 'topicos#adiciona_apostila'
  get '/topicos/remove_apostila/:apostila/:topico', to: 'topicos#remove_apostila'
  get '/material_de_estudo/', to: 'assuntos#assuntos'
  get '/material_de_estudo/:assunto', to: 'assuntos#assunto'
  get '/material_de_estudo/flashcards/:nome_do_deck', to: 'decks#show_por_titulo'
  
  get '/flashcard/img/:id', to: 'flashcards#img'

  
  get 'landing/main'
  
  get '/blog', to: 'blog#inicio'
  get '/marktex_editor/', to: 'blog#marktex_editor'
  

  get 'adiciona_questao/:questao/:apostila', to: 'apostilas#adiciona_questao' #AJAX
  get 'remove_questao/:questao/:apostila', to: 'apostilas#remove_questao' #AJAX

  get 'assuntos/adiciona/:assunto/:questao', to: 'questoes#add_assunto'
  get 'assuntos/remove/:assunto/:questao', to: 'questoes#rem_assunto'
  get 'questao/define_gabarito/:id/:gabarito', to: 'questoes#define_gabarito' #AJAX
  get 'questao/exibir_formulario/:id', to: 'questoes#modal_classificacao' #AJAX
  get '/importar_questoes', to: 'questoes#importar'
  
  get 'sessions/novo-curso/:novo_curso', to: 'sessions#seleciona_curso'
  
  resources :respostas
  resources :questoes
  
  scope '/admin' do
    resources :assuntos
    resources :taticas
    resources :cartoes
    resources :flashcards
    resources :comentarios
    resources :cursos
    resources :topicos
    resources :apostilas
    resources :decks
    resources :concursos
    resources :respostas_fs
    resources :semanas
    resources :estudos
  end

end

app/models/semana.rb
class Semana
  include Mongoid::Document
  field :titulo, type: String
  field :inicio

  has_many :topicos
  has_many :taticas
  has_many :apostilas

  def to_label
  	"#{self.titulo}"
  end
end

app/controllers/semanas_controller.rb
class SemanasController < ApplicationController
  before_action :set_semana, only: [:show, :edit, :update, :destroy]

  # GET /semanas
  # GET /semanas.json
  def index
    @semanas = Semana.all
  end

  # GET /semanas/1
  # GET /semanas/1.json
  def show
  end

  # GET /semanas/new
  def new
    @semana = Semana.new
  end

  # GET /semanas/1/edit
  def edit
  end

  # POST /semanas
  # POST /semanas.json
  def create
    @semana = Semana.new(semana_params)

    respond_to do |format|
      if @semana.save
        format.html { redirect_to @semana, notice: 'Semana was successfully created.' }
        format.json { render :show, status: :created, location: @semana }
      else
        format.html { render :new }
        format.json { render json: @semana.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semanas/1
  # PATCH/PUT /semanas/1.json
  def update
    respond_to do |format|
      if @semana.update(semana_params)
        format.html { redirect_to @semana, notice: 'Semana was successfully updated.' }
        format.json { render :show, status: :ok, location: @semana }
      else
        format.html { render :edit }
        format.json { render json: @semana.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semanas/1
  # DELETE /semanas/1.json
  def destroy
    @semana.destroy
    respond_to do |format|
      format.html { redirect_to semanas_url, notice: 'Semana was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semana
      @semana = Semana.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def semana_params
      params.require(:semana).permit(:titulo, :inicio)
    end
end

app/helpers/semanas_helper.rb
module SemanasHelper
end

app/views/semanas/_card.html.erb
<div class="three wide column">
  <div class="ui fluid link card landing-card">
    <div class="center aligned content">
      <p><%=titulo%></p>  
    </div>
    <div class="content">
      <div class="right floated">
        <i class="star icon"></i>
      </div>
        <h4 class="header">Topico <%=%></h4>      
      
    </div>
  </div>
</div>

app/views/semanas/_form.html.erb
<%= simple_form_for(@semana) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :inicio %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/semanas/_semana.html.erb
<div class="row">
  <h2><%=semana.titulo%></h2>
</div>

<div class="ui divider semana"></div>
<div class="row">
  
  <div class="ui sixteen column grid">
    
    <%semana.topicos.each do |t|%>
      <%=render partial: "semanas/card", locals:{titulo: t.titulo}%>
    <%end%>
    
  </div>
</div>

app/views/semanas/edit.html.erb
<h1>Editing Semana</h1>

<%= render 'form' %>

<%= link_to 'Show', @semana %> |
<%= link_to 'Back', semanas_path %>

app/views/semanas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Semanas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Lancamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @semanas.each do |semana| %>
      <tr>
        <td><%= semana.titulo %></td>
        <td><%= semana.lancamento %></td>
        <td><%= link_to 'Show', semana %></td>
        <td><%= link_to 'Edit', edit_semana_path(semana) %></td>
        <td><%= link_to 'Destroy', semana, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Semana', new_semana_path %>

app/views/semanas/new.html.erb
<h1>New Semana</h1>

<%= render 'form' %>

<%= link_to 'Back', semanas_path %>

app/views/semanas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @semana.titulo %>
</p>

<p>
  <strong>Lancamento:</strong>
  <%= @semana.lancamento %>
</p>

<%= link_to 'Edit', edit_semana_path(@semana) %> |
<%= link_to 'Back', semanas_path %>