config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'landing#main'
  
  get 'plano_de_estudo' => 'landing#painel'
  
  
  
  get 'provas_e_simulados' => 'apostilas#apostilas'
  get '/provas_e_simulados/:apostila/', to: 'apostilas#apostila'
  get '/provas_e_simulados/:apostila/:indice', to: 'apostilas#pagina'
  get '/corrige_cartao/:apostila', to: 'apostilas#corrige_cartao'
  
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'login' => 'landing#login'
  
  get '/topicos/adiciona_apostila/:apostila/:topico', to: 'topicos#adiciona_apostila'
  get '/topicos/remove_apostila/:apostila/:topico', to: 'topicos#remove_apostila'
  get '/material_de_estudo/', to: 'assuntos#assuntos'
  get '/material_de_estudo/:assunto', to: 'assuntos#assunto'
  get '/material_de_estudo/flashcards/:nome_do_deck', to: 'decks#show_por_titulo'
  
  get '/flashcard/img/:id', to: 'flashcards#img'

  
  get 'landing/main'
  
  get '/blog', to: 'blog#inicio'
  get '/marktex_editor/', to: 'blog#marktex_editor'
  

  get 'adiciona_questao/:questao/:apostila', to: 'apostilas#adiciona_questao' #AJAX
  get 'remove_questao/:questao/:apostila', to: 'apostilas#remove_questao' #AJAX

  get 'assuntos/adiciona/:assunto/:questao', to: 'questoes#add_assunto'
  get 'assuntos/remove/:assunto/:questao', to: 'questoes#rem_assunto'
  get 'questao/define_gabarito/:id/:gabarito', to: 'questoes#define_gabarito' #AJAX
  get 'questao/exibir_formulario/:id', to: 'questoes#modal_classificacao' #AJAX
  get '/importar_questoes', to: 'questoes#importar'
  
  get 'sessions/novo-curso/:novo_curso', to: 'sessions#seleciona_curso'
  
  resources :respostas
  resources :questoes
  
  scope '/admin' do
    resources :assuntos
    resources :taticas
    resources :cartoes
    resources :flashcards
    resources :comentarios
    resources :cursos
    resources :topicos
    resources :apostilas
    resources :decks
    resources :concursos
    resources :respostas_fs
    resources :semanas
    resources :estudos
  end

end

app/models/topico.rb
class Topico
  include Mongoid::Document
  field :nome, type: String
  field :titulo, type: String
  field :texto, type: String
  field :indice, type: Float
  field :exemplo, type: String
  field :testes, type: Array, default: []
  
  belongs_to :assunto
  belongs_to :semana
  has_many :comentarios
  has_many :flashcards
  
  default_scope { order_by(:indice => 'asc') }
  
  def to_label
    "#{self.titulo}"
  end
  
  def link
    "/material_de_estudo/#{self.assunto.nome}/#{self.nome}"
  end
end

app/controllers/topicos_controller.rb
class TopicosController < ApplicationController
  before_action :set_topico, only: [:show, :edit, :update, :destroy]
  before_action :set_semanas, only: [:edit]
  before_action :admin_only
  
  def admin_only
    if !current_user.admin
      redirect_to "/"
    end
  end
  
  # GET /topicos
  # GET /topicos.json
  def index
    @topicos = Topico.all
  end

  # GET /topicos/1
  # GET /topicos/1.json
  def show
    @assunto = Assunto.find_by(id: @topico.assunto)
  end
  
  def importar
    def contentful
      @client ||= Contentful::Client.new(
        access_token: "196f7e214bc56b834401b191907a021fd2ce2ec377c0854e63078910843857dd",
        space: "h8r98awupeov",
        dynamic_entries: :auto,
        raise_errors: true
      )
    end
    
    topicos = contentful.entries(content_type: "topico")
    
    topicos.each do |t|
      logger.debug "##########"
      logger.debug t.assunto
      logger.debug "##########"
      filho = Topico.where(nome: t.id)
      
      if filho.size == 0 then
        top = Topico.create! nome: t.id, titulo: t.titulo, texto: t.conteudo
      
        assunto = Assunto.where(nome: t.assunto.nome)
        if assunto.size > 0 then
          assunto = assunto.first
          top.assunto = assunto
          top.save
        end
      end
    end
    
    redirect_to '/topicos/'
  end

  # GET /topicos/new
  def new
    @topico = Topico.new
    @assuntos = Assunto.all
    @apostilas = Apostila.all
  end

  # GET /topicos/1/edit
  def edit
    @assuntos = Assunto.all
    @apostilas = Apostila.all
  end

  # POST /topicos
  # POST /topicos.json
  def create
    @topico = Topico.new(topico_params)
    
    respond_to do |format|
      if @topico.save
        format.html { redirect_to "/topicos/new", notice: 'Topico was successfully created.' }
        format.json { render :show, status: :created, location: @topico }
      else
        format.html { render :new }
        format.json { render json: @topico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topicos/1
  # PATCH/PUT /topicos/1.json
  def update
    respond_to do |format|
      if @topico.update(topico_params)
        format.html { redirect_to @topico, notice: 'Topico was successfully updated.' }
        format.json { render :show, status: :ok, location: @topico }
      else
        format.html { render :edit }
        format.json { render json: @topico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topicos/1
  # DELETE /topicos/1.json
  def destroy
    @topico.destroy
    respond_to do |format|
      format.html { redirect_to topicos_url, notice: 'Topico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def adiciona_apostila
    @apostila = Apostila.find_by(id: params[:apostila])
    @topico = Topico.find_by(id: params[:topico])
    
    if not @topico.testes.include?(@apostila.id)
      @topico.testes.push(@apostila.id)
      @topico.save
    end
    
    redirect_to edit_topico_path(@topico)
  end
  
  def remove_apostila
    @apostila = Apostila.find_by(id: params[:apostila])
    @topico = Topico.find_by(id: params[:topico])
    
    @topico.testes.delete(@apostila.id)
    @topico.save
    redirect_to edit_topico_path(@topico)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topico
      @topico = Topico.find(params[:id])
    end

    def set_semanas
      @semanas = Semana.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topico_params
      params.require(:topico).permit(:nome, :assunto, :titulo, :texto, :exemplo, :testes, :indice, :semana_id)
    end
    
end

app/helpers/topicos_helper.rb
module TopicosHelper
end

app/views/topicos/_form.html.erb
<div class="ui main text container">
  <%= simple_form_for(@topico) do |f| %>
    <%= f.error_notification %>
  
    <div class="form-inputs">
      <%= f.input :nome %>
      <%= f.input :indice %>
      <%= f.input :assunto, collection: @assuntos, label_method: :to_label %>
      <%= f.input :titulo %>
      <%= f.input :texto, as: :text%>
      <%= f.input :semana_id, collection: @semanas %>
      <%= f.input :exemplo, as: :trix_editor %>
      <%= f.input :testes, collection: @apostilas, label_method: :to_label, as: :check_boxes%>
    </div>
    
    <div class="ui segment">
      <div class="form-inputs">
        <h3>Exercícios</h3>
        <select class="ui search dropdown" id="sel_apostila">
          <%@apostilas.each do |a|%>
            <option value="<%=a.id%>"><%=a.display%></option>
          <%end%>
        </select>
        <a class="button" id="botao_add">Adicionar</a>
      </div>
    </div>
  
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>
<script>
  $('#sel_apostila').change(function(){
    var apos = $('#sel_apostila').val();
    $('#botao_add').attr("href", "/topicos/adiciona_apostila/"+apos+"/<%=@topico.id%>");
  });
  $(document).ready(function(){
    <%if Assunto.where(id: @topico.assunto).size > 0 %>
      $("#topico_assunto").val("<%=@topico.assunto.id%>");
    <%end%>
  });
</script>

app/views/topicos/_show.html.erb
<h3 class="ui center aligned header"><%=@topico.titulo%></h3>

<%topico = contentful.entries(content_type: "topico", 'fields.id': @topico.nome)%>
<%if topico.size > 0%>
    <div class="basic segment" id="topico" align="justify">
      <%=topico.first.conteudo.markdown_to_html%>
    </div>
<%else%>
  Conteúdo ainda não disponível
<%end%>

<%if @testes.size > 0%>

  <h4 class="ui header">Exercícios propostos</h4>

  <div class="ui list">
    <%@testes.each do |t|%>
      <a href="<%=t.link%>" class="item">
        <i class="blue book icon"></i>
        <div class="content">
          <div class="header"><%=t.display%></div>
          <div class="description"><%=t.descricao%></div>
        </div>
      </a>
    <%end%>
  </div>
<%end%>

app/views/topicos/_topicos.html.erb
<div class="ui divided selection list">
  <h3>Revisar</h3>
  <%topicos.each do |topico|%>
    <div class="item">
      <div class="header">
        <i class="file text outline icon"></i>
        <a href="<%=topico[0].link%>"><%=topico[0].assunto.display%> -> <%=topico[0].titulo%></a>
      </div>
      <div class="content">
        <%if topico[2]>0 %>
          Aproveitamento: <%= ((topico[1].to_f / (topico[2]+topico[1])).round(2)*100).round(0) %>%
        <%else%>
          Aproveitamento: 100% (Parabéns!!!)
        <%end%>
      </div>
    </div>
  <%end%>
</div>

app/views/topicos/edit.html.erb
<h1>Editing Topico</h1>

<%= render 'form' %>

<%= link_to 'Show', @topico %> |
<%= link_to 'Back', topicos_path %>

app/views/topicos/index.html.erb
<div class="ui main container">
  <p id="notice"><%= notice %></p>
  
  <h1>Lista de Tópicos</h1>
  
  <table class="ui selectable celled compact table">
    <thead>
      <tr>
        <th>Índice</th>
        <th>Titulo</th>
        <th colspan="3">Ações</th>
      </tr>
    </thead>
  
    <tbody>
      <% @topicos.each do |topico| %>
        <tr>
          <td><%=topico.indice%></td>
          <td><%=topico.titulo%></td>
          <td><%= link_to 'Show', topico %></td>
          <td><%= link_to 'Edit', edit_topico_path(topico) %></td>
          <td><%= link_to 'Destroy', topico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Topico', new_topico_path %>
</div>

app/views/topicos/new.html.erb
<h1>New Topico</h1>

<%= render 'form' %>

<%= link_to 'Back', topicos_path %>

app/views/topicos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="ui main grid container">
  
  <div class="row">
    <div class="ui container">
      <h1 class="ui blue header" style="font-family: 'Poppins', sans-serif;">
        <i class="arrow alternate outline circle left icon"></i>
        Material de Estudo
      </h1>
      <div class="ui divider"></div>
      <div class="ui breadcrumb">
        <a href="/material_de_estudo" class="section">Material de Estudo</a>
        <span class="divider">/</span>
        <a href="/material_de_estudo/<%=@assunto.nome%>" class="section"><%=@assunto.display%></a>
        <span class="divider">/</span>
        <div class="active section"><%=@topico.titulo%></div>
      </div><!--Fim do Breadcumb-->
    </div>
  </div>
  
  
  <div class="content row">
    
    <div class="four wide column">
      <div class="ui vertical secondary pointing menu">
        <div class="item">
          <b><%=@assunto.display%></b>
          <div class="menu">
            <%@assunto.topicos.each do |t|%>
              <%ativo = ""%>
              <%if t.id == @topico.id%>
                <%ativo = "active"%>
              <%end%>
              <a class="item <%=ativo%>" href="<%="/material_de_estudo/#{@assunto.nome}/#{t.nome}"%>">
                <%=t.titulo%>
              </a>
            <%end%>
          </div>
        </div>
      </div>
    </div>
    
    <div class="twelve wide column">
      <div class="ui basic segment">
        
        <h3 class="ui left aligned header">Cartões:</h3>
        <div class="ui segment">
          <%= @topico.texto%>
        </div>
        <a href="<%=edit_topico_path @topico%>/">Editar</a>
      </div>
    </div>

  </div>
</div>
  <script>
    $('.ui.rating')
      .rating('disable')
    ;
  
    loadMathJax();
    $(document).on('page:load', loadMathJax())
    
    function loadMathJax(){
      window.MathJax = null;
      $.getScript("https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML", function(){
        MathJax.Hub.Config({
          tex2jax: {
            showMathMenu: false,
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            processEscapes: true
          }
        });
      })
      MathJax.Hub.Queue(["Typeset", MathJax.Hub])
    }
  </script>

app/views/topicos/show.js.erb
$('#topico_conteudo').html('<%= j render 'topicos/show'%>');

app/views/topicos/show_c.html.erb
<p id="notice"><%= notice %></p>

<div class="ui main grid container">
  <div class="row">
    <div class="column">
      <div class="ui teal header">
          <img src="/assets/conjuntos.svg"></img>
          <div class="content">
            <%= @assunto.display %> > <u><%= @topico.titulo%></u>
          </div>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="two wide column"></div>
    <div class="twelve wide column">
      
      <div class="row">
        <div class="ui secondary menu">
          <a class="teal item active" data-tab="first">Resumo</a>
          <a class="teal item" data-tab="second">Exemplos</a>
          <a class="teal item" data-tab="third">Exercicios</a>
          <a class="teal item" data-tab="fourth">Desempenho</a>
        </div>
      </div>
      
        <div class="ui tab segment active" data-tab="first">
          <h2 class="ui center aligned header"><%=@topico.titulo%></h2>
          <div class="ui basic segment"><%=@topico.texto.html_safe%></div>
        </div>
        
        <div class="ui tab segment" data-tab="second">
          <h2 class="ui center aligned header">Exemplos</h2>
          <div class="ui segment">

          </div>
        </div>
        
        <div class="ui tab segment" data-tab="third">
          <h2 class="ui center aligned header">Exercícios</h2>
          
          <%if @testes.size > 0%>
            <% i = 0 %>
            <%@testes.each do |q|%>
              <%@questao = q%>
              <%@resposta = @respostas[i]%>
              <div class="ui segment">
                <%= render 'questoes/show'%>
              </div>
              <%i += 1%>
            <%end%>
          <%end%>
          
        </div>
        
        <div class="ui tab segment" data-tab="fourth">
          <h2 class="ui center aligned header">Desempenho</h2>
          
        </div>
      
    </div>
    <div class="two wide column"></div>
  </div>
  
  <div class="row">

    <div class="eight wide column">
      
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_topico_path(@topico) %> |
<%= link_to 'Back', topicos_path %>

<script>
  $(document).ready(function(){
    $('.menu .item')
      .tab()
    ;
  });
</script>

<%= content_for :head do %>
  <%= stylesheet_link_tag 'questoes', media: 'all', 'data-turbolinks-track' => true %>
  
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        inlineMath: [ ['$','$'], ["\\(","\\)"] ],
        processEscapes: true
      }
    });
  </script>
  
  <script type="text/javascript" async
    src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML">
  </script>
<%end%>